### ISSUE TITLE
[1.16.5] Game crashes when attempting to load a world with enhanced celestials installed

### ISSUE THREAD

**Issue by NJL5390** [Fuzss/respawnableanimals#2]
Hi,
I've just added this mod to my modpack and have found that the game crashes whenever I attempt to even load a world with this mod installed.  After doing some testing I've found that this crash does not occur with this mod alone and is definitely the result of an interaction with another mod. I'm not sure which mod is causing it at this stage, but I will report this crash nonetheless.

Minecraft version: 1.16.5
Forge version: 36.0.7

Crash Report: 
[crash-2021-01-27_20.29.15-server.txt](https://github.com/Fuzss/respawnableanimals/files/5883004/crash-2021-01-27_20.29.15-server.txt)

Latest Game log:
[latest.log](https://github.com/Fuzss/respawnableanimals/files/5883010/latest.log)

I will let you know if I am able to find anything else out about this crash.
Let me know if there's any more information that you need from me.

**Comment by NJL5390** [comment]
Update: I have found out which mod is causing this issue! It's a mod called enhanced celestials!

Here are the logs and crash report generated by the issue with just these two mods:
[latest.log](https://github.com/Fuzss/respawnableanimals/files/5884007/latest.log)
[crash-2021-01-28_00.41.11-server.txt](https://github.com/Fuzss/respawnableanimals/files/5884009/crash-2021-01-28_00.41.11-server.txt)

**Comment by NJL5390** [comment]
Update: I've created an issue on their github as well:
https://github.com/CorgiTaco/Enhanced-Celestials/issues/5

**Comment by BugmanBugman** [comment]
https://hatebin.com/pfnrhmtcks
Getting this as well

**Comment by Fuzss** [comment]
Fixed in v1.0.2. You may close the other issue.
