### ISSUE TITLE
[1.16.5] Mobs from Endergetic Expansion spawn constantly and build up to ridiculous quantities when this mod is installed

### ISSUE THREAD

**Issue by NJL5390** [Fuzss/respawnableanimals#3]
Minecraft Version: 1.16.5
Forge Version: 36.0.13
Respawnable Animals Version: 1.0.2
Endergetic Expansion Version: 3.0.0
Abnormals Core Version: 3.0.6

Latest Client Log: https://pastebin.com/2vWLiDZh

Hi,
I've noticed that whenever I have Respawnable Animals installed, mobs from the Endergetic Expansion will constantly spawn and build up to huge quantities when in or near that mod's poise forest biome, forcing me to either leave the area or kill all the mobs using a command to prevent my game from lagging out and crashing. Every other mod I've used has worked just fine with Respawnable Animals. This is the only mod that has been causing me some problems with Respawnable Animals. (Aside from Enhanced Celestials), So it's entirely possible it could be something in their end but I'm reporting it here since your mod seems to make the most changes to general mob spawning.

This issue happens regardless of what mobs are on the blacklist in the config file.

Here are some screenshots to illustrate the problem:
![2021-01-31_14 54 36](https://user-images.githubusercontent.com/64381954/106388261-9beb3900-63d5-11eb-83ef-fd4e0b85be38.png)
![2021-01-31_14 33 23](https://user-images.githubusercontent.com/64381954/106388278-ac031880-63d5-11eb-900e-cef26a923cbd.png)

Here's a link to the mod's page in case you need it: https://www.curseforge.com/minecraft/mc-mods/endergetic

(Update: I've posted the issue to their github: https://github.com/team-abnormals/endergetic/issues/144)

**Comment by Fuzss** [comment]
Core issue is still present in Endergetic Expansion (different entity classifications used for registering and spawning), but at least now Respawnable Animals won't make it any worse.
