### ISSUE TITLE
Error Code: 0 Crashes

### ISSUE THREAD

**Issue by YnwLNE** [Fuzss/respawnableanimals#7]
Happens upon bootup. It gets to about 4 seconds in before crashing to launcher with an error code: 0. Because of this I can't provide a crash log as it won't generate one even with not enough crashes. Here's my mod list. 

https://pastebin.com/rEfDj152

**Comment by Fuzss** [comment]
There will still be a log though, that’s what I need. You can find it at `.minecraft/logs/latest.log`.

**Comment by Fuzss** [comment]
Closing this as not log was provided.
